In [8]:
import pandas as pd
import numpy as np

data = {
    'Customer_ID': [101, 102, 103, 104, 105, 105, 107, 108, 109, 110],
    'Name': [' Anish ', ' Rahul', 'Sreeja', 'Devanand', ' Maya ', ' Maya ', 'Arun', ' Kavya', 'Nikhil', 'Priya'],
    'Age': [25, np.nan, 30, 22, 28, 28, 150, 24, np.nan, 29], # 150 എന്നത് ഒരു Outlier ആണ്
    'Gender': ['Male', 'male', 'F', 'M', 'Female', 'Female', 'M', 'Female', 'male', 'F'],
    'Joining_Date': ['2023-01-15', '15/01/2023', '2023-02-20', '2023-03-10', '2023-03-12', '2023-03-12', '2023/04/01', np.nan, '2023-05-18', '2023-06-22'],
    'Salary': ['50000', '60000', ' 55000 ', '70000', '65000', '65000', '80000', np.nan, '48000', '75000']
}

df_messy = pd.DataFrame(data)
df_messy.to_csv("messy_dataset.csv", index=False)
print("Messy Dataset Successfully Created!")

Messy Dataset Successfully Created!

In [9]:
# Load messy data
df = pd.read_csv("messy_dataset.csv")
print("2. Initial Messy Data:")
df

2. Initial Messy Data:

   Customer_ID      Name    Age  Gender Joining_Date   Salary
0          101    Anish    25.0    Male   2023-01-15  50000.0
1          102     Rahul    NaN    male   15/01/2023  60000.0
2          103    Sreeja   30.0       F   2023-02-20  55000.0
3          104  Devanand   22.0       M   2023-03-10  70000.0
4          105     Maya    28.0  Female   2023-03-12  65000.0
5          105     Maya    28.0  Female   2023-03-12  65000.0
6          107      Arun  150.0       M   2023/04/01  80000.0
7          108     Kavya   24.0  Female          NaN      NaN
8          109    Nikhil    NaN    male   2023-05-18  48000.0
9          110     Priya   29.0       F   2023-06-22  75000.0

In [10]:
print("--- Data Quality Report ---")
print("1. Total Rows & Columns:", df.shape)
print("\n2. Null Values Count:\n", df.isnull().sum())
print("\n3. Duplicate Rows Count:", df.duplicated().sum())
print("\n4. Data Types:\n", df.dtypes)

--- Data Quality Report ---
1. Total Rows & Columns: (10, 6)

2. Null Values Count:
 Customer_ID     0
Name            0
Age             2
Gender          0
Joining_Date    1
Salary          1
dtype: int64

3. Duplicate Rows Count: 1

4. Data Types:
 Customer_ID       int64
Name                str
Age             float64
Gender              str
Joining_Date        str
Salary          float64
dtype: object

In [11]:

df_clean = df.drop_duplicates().copy()

df_clean['Name'] = df_clean['Name'].astype(str).str.strip()

df_clean['Gender'] = df_clean['Gender'].astype(str).str.strip().str.upper()
df_clean['Gender'] = df_clean['Gender'].replace({'M': 'Male', 'MALE': 'Male', 'F': 'Female', 'FEMALE': 'Female'})

df_clean['Salary'] = pd.to_numeric(df_clean['Salary'].astype(str).str.strip(), errors='coerce')

df_clean['Salary'] = df_clean['Salary'].fillna(df_clean['Salary'].median())
df_clean['Age'] = pd.to_numeric(df_clean['Age'], errors='coerce')
df_clean['Age'] = df_clean['Age'].fillna(df_clean['Age'].median())

df_clean.loc[df_clean['Age'] > 100, 'Age'] = df_clean['Age'].median()

df_clean['Joining_Date'] = pd.to_datetime(df_clean['Joining_Date'], errors='coerce')
df_clean['Joining_Date'] = df_clean['Joining_Date'].ffill()

print("Cleaned Dataset:")
df_clean

Cleaned Dataset:

   Customer_ID      Name   Age  Gender Joining_Date   Salary
0          101     Anish  25.0    Male   2023-01-15  50000.0
1          102     Rahul  28.0    Male   2023-01-15  60000.0
2          103    Sreeja  30.0  Female   2023-02-20  55000.0
3          104  Devanand  22.0    Male   2023-03-10  70000.0
4          105      Maya  28.0  Female   2023-03-12  65000.0
6          107      Arun  28.0    Male   2023-03-12  80000.0
7          108     Kavya  24.0  Female   2023-03-12  62500.0
8          109    Nikhil  28.0    Male   2023-05-18  48000.0
9          110     Priya  29.0  Female   2023-06-22  75000.0

In [12]:
summary_data = {
    'Metric': ['Total Rows', 'Duplicate Rows', 'Null Values in Age', 'Null Values in Salary'],
    'Before Cleaning': [len(df), df.duplicated().sum(), df['Age'].isnull().sum(), df['Salary'].isnull().sum()],
    'After Cleaning': [len(df_clean), df_clean.duplicated().sum(), df_clean['Age'].isnull().sum(), df_clean['Salary'].isnull().sum()]
}

summary_df = pd.DataFrame(summary_data)
print("--- Before vs After Summary ---")
print(summary_df)

df_clean.to_csv("cleaned_dataset.csv", index=False)
print("\nCleaned dataset saved as 'cleaned_dataset.csv'!")

--- Before vs After Summary ---
                  Metric  Before Cleaning  After Cleaning
0             Total Rows               10               9
1         Duplicate Rows                1               0
2     Null Values in Age                2               0
3  Null Values in Salary                1               0

Cleaned dataset saved as 'cleaned_dataset.csv'!